# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodonUsage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size', blank=True)),
                ('aa', models.TextField(verbose_name=b'Amino acids')),
                ('AUU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AUC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AUA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CUU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CUC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CUA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CUG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UUA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CAA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CAG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GUU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GUC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GUA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GUG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UUU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UUC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AUG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UGU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UGC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GCU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GCC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GCA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GCG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GGU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GGC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GGA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GGG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CCU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CCC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CCA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CCG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('ACU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('ACC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('ACA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('ACG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UCU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UCC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UCA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UCG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AGU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AGC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UAU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UAC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UGG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UUG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AAU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AAC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CAU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CAC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GAA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GAG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GAU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('GAC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AAA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AAG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CGU', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CGC', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CGA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('CGG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AGA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('AGG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UAA', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UAG', models.IntegerField(max_length=11, null=True, blank=True)),
                ('UGA', models.IntegerField(max_length=11, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MitoAgeEntry',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bc_total_mtDNA_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of total mtDNA', blank=True)),
                ('bc_total_mtDNA_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_total_mtDNA_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_total_mtDNA_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_total_mtDNA_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_total_mtDNA_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_total_mtDNA_pc_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of protein-coding region of mtDNA', blank=True)),
                ('bc_total_mtDNA_pc_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_total_mtDNA_pc_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_total_mtDNA_pc_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_total_mtDNA_pc_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_total_mtDNA_bc_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_d_loop_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of D-loop region', blank=True)),
                ('bc_d_loop_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_d_loop_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_d_loop_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_d_loop_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_d_loop_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_total_rRNA_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of rRNA region of mtDNA', blank=True)),
                ('bc_total_rRNA_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_total_rRNA_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_total_rRNA_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_total_rRNA_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_total_rRNA_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_atp6_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_atp6_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_atp6_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_atp6_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_atp6_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_atp6_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_atp8_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_atp8_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_atp8_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_atp8_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_atp8_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_atp8_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_cox1_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_cox1_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_cox1_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_cox1_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_cox1_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_cox1_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_cox2_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_cox2_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_cox2_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_cox2_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_cox2_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_cox2_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_cox3_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_cox3_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_cox3_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_cox3_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_cox3_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_cox3_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_cytb_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_cytb_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_cytb_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_cytb_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_cytb_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_cytb_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_nd1_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_nd1_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_nd1_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_nd1_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_nd1_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_nd1_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_nd2_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_nd2_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_nd2_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_nd2_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_nd2_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_nd2_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_nd3_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_nd3_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_nd3_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_nd3_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_nd3_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_nd3_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_nd4_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_nd4_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_nd4_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_nd4_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_nd4_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_nd4_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_nd4l_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_nd4l_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_nd4l_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_nd4l_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_nd4l_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_nd4l_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_nd5_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_nd5_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_nd5_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_nd5_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_nd5_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_nd5_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_nd6_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of gene', blank=True)),
                ('bc_nd6_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_nd6_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_nd6_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_nd6_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_nd6_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_rRNA_12S_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of ribosomal subunit', blank=True)),
                ('bc_rRNA_12S_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_rRNA_12S_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_rRNA_12S_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_rRNA_12S_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_rRNA_12S_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('bc_rRNA_16S_size', models.IntegerField(max_length=11, null=True, verbose_name=b'Size of ribosomal subunit', blank=True)),
                ('bc_rRNA_16S_g', models.IntegerField(max_length=11, null=True, verbose_name=b'G content', blank=True)),
                ('bc_rRNA_16S_c', models.IntegerField(max_length=11, null=True, verbose_name=b'C content', blank=True)),
                ('bc_rRNA_16S_t', models.IntegerField(max_length=11, null=True, verbose_name=b'T content', blank=True)),
                ('bc_rRNA_16S_a', models.IntegerField(max_length=11, null=True, verbose_name=b'A content', blank=True)),
                ('bc_rRNA_16S_others', models.IntegerField(max_length=11, null=True, verbose_name=b'Other', blank=True)),
                ('species', models.ForeignKey(related_name=b'mitoage_entries', to='taxonomy.TaxonomySpecies')),
            ],
            options={
                'verbose_name': 'MitoAge entry',
                'verbose_name_plural': 'MitoAge entries',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_atp6_entry',
            field=models.OneToOneField(related_name=b'atp6_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_atp8_entry',
            field=models.OneToOneField(related_name=b'atp8_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_cox1_entry',
            field=models.OneToOneField(related_name=b'cox1_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_cox2_entry',
            field=models.OneToOneField(related_name=b'cox2_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_cox3_entry',
            field=models.OneToOneField(related_name=b'cox3_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_cytb_entry',
            field=models.OneToOneField(related_name=b'cytb_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_nd1_entry',
            field=models.OneToOneField(related_name=b'nd1_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_nd2_entry',
            field=models.OneToOneField(related_name=b'nd2_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_nd3_entry',
            field=models.OneToOneField(related_name=b'nd3_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_nd4_entry',
            field=models.OneToOneField(related_name=b'nd4_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_nd4l_entry',
            field=models.OneToOneField(related_name=b'nd4l_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_nd5_entry',
            field=models.OneToOneField(related_name=b'nd5_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_nd6_entry',
            field=models.OneToOneField(related_name=b'nd6_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codonusage',
            name='cu_protein_coding_entry',
            field=models.OneToOneField(related_name=b'protein_coding_codon_usage', null=True, blank=True, to='analysis.MitoAgeEntry'),
            preserve_default=True,
        ),
    ]
